### ISSUE TITLE
json2php is now written in TypeScript

### ISSUE THREAD

**Issue by daniel-zahariev** [mrOttoW/vite-php-asset-file#1]
https://github.com/mrOttoW/vite-php-asset-file/blob/5f663da3e812daae7c93fb987576bba3d6f60424/types/json2php.d.ts#L2

Hi,
thank you for using json2php package. 
I spent some time over the weekend to migrate it from Coffeescript to TypeScript, so you shouldn't need the the TS definition file any more.

Best,
Daniel

**Comment by mrOttoW** [comment]
Hi @daniel-zahariev , 

Thanks for letting me know and the effort migrating to TypeScript, that’s a nice win.  I’ll update my package to reflect the changes. Appreciate the package!
